# Path: .github/workflows/compatibility-check.yaml
# Desc: Premake Project Files Generation Workflow
# Auth: thedevmystic <thedevmystic@gmail.com>
name: Compatibility Check

on:
  push: # Trigger on pushes
    branches:
      - main
      - feat/**
      - fix/**
  workflow_dispatch: # Allow manual trigger
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: windows-latest
            os_name: windows
            premake_path: Vendor/Binaries/Premake/Windows/premake5.exe
            premake_action: vs2022
            build_command: msbuild EsoProg.sln /p:Configuration=Release /p:Platform=x64
          - os: ubuntu-latest
            os_name: linux
            premake_path: Vendor/Binaries/Premake/Linux/premake5
            premake_action: gmake
            build_command: make config=release
          - os: macos-latest
            os_name: macos
            premake_path: Vendor/Binaries/Premake/macOS/premake5
            premake_action: gmake
            build_command: make config=release

    steps:
      - name: Checkout Repository and Submodules
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Install Linux/macOS Dependencies & Set Permissions
        if: runner.os != 'Windows'
        run: |
          if [ "${{ runner.os }}" == "Linux" ]; then sudo apt update && sudo apt install -y g++; fi
          chmod +x ${{ matrix.premake_path }}

      - name: Generate Project Files (Release)
        run: ${{ matrix.premake_path }} ${{ matrix.premake_action }} --file="Build.lua"
        working-directory: ${{ github.workspace }}

      # ----------------------------------------------------------------------
      # BUILD STEP 1: Windows
      # ----------------------------------------------------------------------
      - name: Build Executable (Release) - Windows MSBuild
        if: runner.os == 'Windows'
        shell: cmd # Forces the use of the Command Prompt shell
        run: |
          REM Find the Visual Studio installation path
          for /f "usebackq tokens=*" %%i in (`"C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe" -latest -products * -property installationPath`) do set VSPATH=%%i
          
          REM Execute the environment setup script to find MSBuild in PATH
          call "%VSPATH%\VC\Auxiliary\Build\vcvars64.bat"

          REM Run the msbuild command in the same shell session
          ${{ matrix.build_command }}

      # ----------------------------------------------------------------------
      # BUILD STEP 2: Linux/macOS (Make)
      # ----------------------------------------------------------------------
      - name: Build Executable (Release) - Unix Make
        if: runner.os != 'Windows'
        run: ${{ matrix.build_command }}
